//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcollection()
        {
            this.tbldeck = new HashSet<tbldeck>();
        }
    
        public int idcollectioncard { get; set; }
        public int fkperson { get; set; }
        public int fkorder { get; set; }
        public int fkcard { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        public virtual tblorder tblorder { get; set; }
        public virtual tblperson tblperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbldeck> tbldeck { get; set; }
    }
}
