//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcollection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcollection()
        {
            this.tbldeck = new HashSet<tbldeck>();
        }
    
        public int idcollectioncard { get; set; }
        public int fkperson { get; set; }
        public int fkorder { get; set; }
        public int fkcard { get; set; }
    
        public virtual tblcard tblcard { get; set; }
        public virtual tblorder tblorder { get; set; }
        public virtual tblperson tblperson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbldeck> tbldeck { get; set; }
    }
}
